// ISO 3166-1 country list — approximately 249 sovereign states and territories.
// Ordered: Gulf + Middle East + South Asia first (most common for visa bookings),
// then remaining countries alphabetically.

export const COUNTRIES: string[] = [
  // Gulf & Middle East (priority)
  'Oman',
  'UAE',
  'Saudi Arabia',
  'Qatar',
  'Bahrain',
  'Kuwait',
  'Iraq',
  'Iran',
  'Jordan',
  'Lebanon',
  'Syria',
  'Yemen',
  'Palestine',
  'Israel',
  'Egypt',
  'Libya',
  'Tunisia',
  'Algeria',
  'Morocco',
  'Sudan',
  'South Sudan',
  'Somalia',
  'Djibouti',
  'Eritrea',

  // South Asia (priority)
  'India',
  'Pakistan',
  'Bangladesh',
  'Sri Lanka',
  'Nepal',
  'Bhutan',
  'Maldives',
  'Afghanistan',

  // Southeast Asia
  'Philippines',
  'Indonesia',
  'Malaysia',
  'Thailand',
  'Singapore',
  'Vietnam',
  'Myanmar',
  'Cambodia',
  'Laos',
  'Brunei',
  'Timor-Leste',

  // East Asia
  'China',
  'Japan',
  'South Korea',
  'North Korea',
  'Hong Kong',
  'Taiwan',
  'Mongolia',

  // Central Asia
  'Kazakhstan',
  'Uzbekistan',
  'Kyrgyzstan',
  'Tajikistan',
  'Turkmenistan',
  'Azerbaijan',
  'Armenia',
  'Georgia',

  // Turkey
  'Turkey',

  // Africa — East
  'Ethiopia',
  'Kenya',
  'Tanzania',
  'Uganda',
  'Rwanda',
  'Burundi',
  'Comoros',
  'Madagascar',
  'Mauritius',
  'Seychelles',
  'Mozambique',
  'Zimbabwe',
  'Zambia',
  'Malawi',

  // Africa — West & Central
  'Nigeria',
  'Ghana',
  'Senegal',
  'Ivory Coast',
  'Cameroon',
  'Democratic Republic of Congo',
  'Republic of Congo',
  'Gabon',
  'Equatorial Guinea',
  'Central African Republic',
  'Chad',
  'Niger',
  'Mali',
  'Burkina Faso',
  'Benin',
  'Togo',
  'Sierra Leone',
  'Liberia',
  'Guinea',
  'Guinea-Bissau',
  'Gambia',
  'Cabo Verde',
  'São Tomé and Príncipe',

  // Africa — Southern
  'South Africa',
  'Botswana',
  'Namibia',
  'Lesotho',
  'Eswatini',
  'Angola',

  // Africa — North (remaining)
  'Mauritania',
  'Western Sahara',

  // Europe — Western
  'United Kingdom',
  'Ireland',
  'France',
  'Germany',
  'Netherlands',
  'Belgium',
  'Luxembourg',
  'Switzerland',
  'Austria',
  'Liechtenstein',
  'Monaco',
  'Andorra',

  // Europe — Southern
  'Spain',
  'Portugal',
  'Italy',
  'San Marino',
  'Vatican City',
  'Malta',
  'Greece',
  'Cyprus',

  // Europe — Northern
  'Sweden',
  'Norway',
  'Denmark',
  'Finland',
  'Iceland',
  'Estonia',
  'Latvia',
  'Lithuania',

  // Europe — Central & Eastern
  'Poland',
  'Czech Republic',
  'Slovakia',
  'Hungary',
  'Romania',
  'Bulgaria',
  'Slovenia',
  'Croatia',
  'Bosnia and Herzegovina',
  'Serbia',
  'Montenegro',
  'North Macedonia',
  'Albania',
  'Kosovo',
  'Moldova',
  'Ukraine',
  'Belarus',
  'Russia',

  // Americas — North
  'United States',
  'Canada',
  'Mexico',

  // Americas — Caribbean
  'Cuba',
  'Jamaica',
  'Haiti',
  'Dominican Republic',
  'Puerto Rico',
  'Trinidad and Tobago',
  'Barbados',
  'Bahamas',
  'Belize',
  'Guatemala',
  'Honduras',
  'El Salvador',
  'Nicaragua',
  'Costa Rica',
  'Panama',

  // Americas — South
  'Colombia',
  'Venezuela',
  'Guyana',
  'Suriname',
  'Brazil',
  'Ecuador',
  'Peru',
  'Bolivia',
  'Chile',
  'Argentina',
  'Uruguay',
  'Paraguay',

  // Oceania
  'Australia',
  'New Zealand',
  'Papua New Guinea',
  'Fiji',
  'Solomon Islands',
  'Vanuatu',
  'Samoa',
  'Tonga',
  'Kiribati',
  'Micronesia',
  'Marshall Islands',
  'Palau',
  'Nauru',
  'Tuvalu',

  // Pacific territories (commonly used for visa purposes)
  'Guam',
  'American Samoa',
  'New Caledonia',
  'French Polynesia',
];

export const COUNTRY_OPTIONS = COUNTRIES.map((c) => ({
  value: c,
  label: c,
}));
