"use client";

import React, { createContext, useContext, useState, useEffect, useCallback } from "react";

type Locale = "en" | "ar";

interface Dictionary {
  [key: string]: string;
}

const en: Dictionary = {
  login: "Login",
  createAccount: "Create Account",
  email: "Email",
  password: "Password",
  forgotPassword: "Forgot password?",
  signIn: "Sign In",
  error: "Something went wrong. Please try again.",
  agencyName: "Agency Name",
  phone: "Phone",
  address: "Address",
  crNumber: "CR / License Number",
  currency: "Currency",
  language: "Language",
  perMonth: "/month",
  totalRevenue: "Total Revenue",
  netProfit: "Net Profit",
  pendingPayments: "Pending Payments",
  totalBookings: "Total Bookings",
  todaysBookings: "Today's Bookings",
  activeAgents: "Active Agents",
  commandCenter: "Command Center",
  welcome: "Welcome",
  revenueChart: "Revenue Overview",
  bookingTypeChart: "Booking Types",
  recentActivity: "Recent Activity",
  agentCommissionOverview: "Agent Commission Overview",
  commission: "Commission",
  bookings: "Bookings",
  customers: "Customers",
  invoices: "Invoices",
  agents: "Agents & Commissions",
  reports: "Reports",
  calendar: "Calendar",
  settings: "Settings",
  admin: "SaaS Admin",
  logout: "Logout",
  newBooking: "New Booking",
  airTicket: "Air Ticket",
  visa: "Visa",
  hotel: "Hotel",
  groupTour: "Group Tour",
  paid: "Paid",
  pending: "Pending",
  refund: "Refund",
  processing: "Processing",
  approved: "Approved",
  rejected: "Rejected",
  issued: "Issued",
  search: "Search",
  filter: "Filter",
  export: "Export",
  save: "Save",
  cancel: "Cancel",
  edit: "Edit",
  delete: "Delete",
  view: "View",
  actions: "Actions",
  yes: "Yes",
  no: "No",
  dashboard: "Dashboard",
  profile: "Agency Profile",
  logo: "Agency Logo",
  invoiceSettings: "Invoice Settings",
  users: "Users & Roles",
  usersRoles: "Users & Roles",
  branches: "Branches",
  whatsapp: "WhatsApp Settings",
  emailSettings: "Email Settings",
  all: "All",
  status: "Status",
  type: "Type",
  amount: "Amount",
  date: "Date",
  customer: "Customer",
  agency: "Agency",
  invoice: "Invoice",
  number: "Number",
  download: "Download",
  send: "Send",
  agent: "Agent",
  sales: "Sales",
  commissionRate: "Commission %",
  earned: "Earned",
  paidCommission: "Paid",
  pendingCommission: "Pending",
  performance: "Performance",
  monthly: "Monthly",
  daily: "Daily",
  weekly: "Weekly",
  yearly: "Yearly",
  total: "Total",
  revenue: "Revenue",
  profit: "Profit",
  cost: "Cost",
  active: "Active",
  inactive: "Inactive",
  trial: "Trial",
  suspended: "Suspended",
  roleOwner: "Owner",
  roleAdmin: "Admin",
  roleManager: "Manager",
  roleAgent: "Agent",
  roleAccountant: "Accountant",
  roleViewer: "Viewer",
  role: "Role",
  plan: "Plan",
  subscription: "Subscription",
  currentPlan: "Current Plan",
  startTrial: "Start Trial",
  upgrade: "Upgrade",
  downgrade: "Downgrade",
  renew: "Renew",
  expire: "Expire",
  contactSales: "Contact Sales",
  demoLimit: "Demo limit reached. Please subscribe to continue using TravelDesk Pro.",
  demo: "Demo",
  rememberMe: "Remember me",
  next: "Next",
  back: "Back",
  submit: "Submit",
  create: "Create",
  add: "Add",
  remove: "Remove",
  close: "Close",
  open: "Open",
  details: "Details",
  notes: "Notes",
  passport: "Passport Info",
  totalSpend: "Total Spend",
  bookingHistory: "Booking History",
  route: "Route",
  pnr: "PNR",
  ticketNumber: "Ticket Number",
  airline: "Airline",
  visaCountry: "Visa Country",
  hotelName: "Hotel Name",
  checkIn: "Check-in",
  checkOut: "Check-out",
  tourName: "Tour Name",
  costPrice: "Cost Price",
  salePrice: "Sale Price",
  agentCommission: "Agent Commission",
  paymentStatus: "Payment Status",
  processStatus: "Process Status",
  createdAt: "Created",
  updatedAt: "Updated",
  quickActions: "Quick Actions",
  generateReport: "Generate Report",
  auditLogs: "Audit Logs",
  agencies: "Agencies",
  subscriptions: "Subscriptions",
  plans: "Plans",
  payments: "Payments",
  usage: "Usage",
  reset: "Reset",
  suspend: "Suspend",
  unsuspend: "Unsuspend",
  deleteAccount: "Delete Account",
  areYouSure: "Are you sure?",
  thisCannotBeUndone: "This action cannot be undone.",
  success: "Success",
  warning: "Warning",
  info: "Info",
  errorOccurred: "An error occurred",
  tryAgain: "Please try again",
  loading: "Loading",
  noData: "No data available",
  noResults: "No results found",
  showMore: "Show more",
  showLess: "Show less",
  itemsPerPage: "Items per page",
  of: "of",
  page: "Page",
  previous: "Previous",
  greeting: "Good morning",
  greetingAfternoon: "Good afternoon",
  greetingEvening: "Good evening",
  agencyProfile: "Agency Profile",
};

const ar: Dictionary = {
  login: "تسجيل الدخول",
  createAccount: "إنشاء حساب",
  email: "البريد الإلكتروني",
  password: "كلمة المرور",
  forgotPassword: "نسيت كلمة المرور؟",
  signIn: "تسجيل الدخول",
  error: "حدث خطأ. يرجى المحاولة مرة أخرى.",
  agencyName: "اسم الوكالة",
  phone: "رقم الهاتف",
  address: "العنوان",
  crNumber: "رقم السجل التجاري",
  currency: "العملة",
  language: "اللغة",
  perMonth: "/شهر",
  totalRevenue: "إجمالي الإيرادات",
  netProfit: "صافي الربح",
  pendingPayments: "المدفوعات المعلقة",
  totalBookings: "إجمالي الحجوزات",
  todaysBookings: "حجوزات اليوم",
  activeAgents: "الوكلاء النشطون",
  commandCenter: "مركز القيادة",
  welcome: "مرحباً",
  revenueChart: "نظرة عامة على الإيرادات",
  bookingTypeChart: "أنواع الحجوزات",
  recentActivity: "النشاط الأخير",
  agentCommissionOverview: "نظرة عامة على عمولة الوكلاء",
  commission: "العمولة",
  bookings: "الحجوزات",
  customers: "العملاء",
  invoices: "الفواتير",
  agents: "الوكلاء والعمولات",
  reports: "التقارير",
  calendar: "التقويم",
  settings: "الإعدادات",
  admin: "إدارة المنصة",
  logout: "تسجيل الخروج",
  newBooking: "حجز جديد",
  airTicket: "تذكرة طيران",
  visa: "تأشيرة",
  hotel: "فندق",
  groupTour: "جولة جماعية",
  paid: "مدفوع",
  pending: "معلق",
  refund: "مسترد",
  processing: "قيد المعالجة",
  approved: "تمت الموافقة",
  rejected: "مرفوض",
  issued: "صادر",
  search: "بحث",
  filter: "تصفية",
  export: "تصدير",
  save: "حفظ",
  cancel: "إلغاء",
  edit: "تعديل",
  delete: "حذف",
  view: "عرض",
  actions: "إجراءات",
  yes: "نعم",
  no: "لا",
  dashboard: "لوحة التحكم",
  profile: "ملف الوكالة",
  logo: "شعار الوكالة",
  invoiceSettings: "إعدادات الفاتورة",
  users: "المستخدمين والأدوار",
  usersRoles: "المستخدمين والأدوار",
  branches: "الفروع",
  whatsapp: "إعدادات واتساب",
  emailSettings: "إعدادات البريد",
  all: "الكل",
  status: "الحالة",
  type: "النوع",
  amount: "المبلغ",
  date: "التاريخ",
  customer: "العميل",
  agency: "الوكالة",
  invoice: "الفاتورة",
  number: "الرقم",
  download: "تحميل",
  send: "إرسال",
  agent: "الوكيل",
  sales: "المبيعات",
  commissionRate: "نسبة العمولة",
  earned: "المكتسبة",
  paidCommission: "المدفوعة",
  pendingCommission: "المعلقة",
  performance: "الأداء",
  monthly: "شهري",
  daily: "يومي",
  weekly: "أسبوعي",
  yearly: "سنوي",
  total: "الإجمالي",
  revenue: "الإيرادات",
  profit: "الربح",
  cost: "التكلفة",
  active: "نشط",
  inactive: "غير نشط",
  trial: "تجربة",
  suspended: "موقوف",
  roleOwner: "المالك",
  roleAdmin: "مدير",
  roleManager: "مدير",
  roleAgent: "وكيل",
  roleAccountant: "محاسب",
  roleViewer: "مشاهد",
  role: "الدور",
  plan: "الخطة",
  subscription: "الاشتراك",
  currentPlan: "الخطة الحالية",
  startTrial: "بدء التجربة",
  upgrade: "ترقية",
  downgrade: "تخفيض",
  renew: "تجديد",
  expire: "انتهاء",
  contactSales: "تواصل مع المبيعات",
  demoLimit: "تم الوصول إلى الحد الأقصى للتجربة. يرجى الاشتراك للاستمرار في استخدام TravelDesk Pro.",
  demo: "تجريبي",
  rememberMe: "تذكرني",
  next: "التالي",
  back: "رجوع",
  submit: "إرسال",
  create: "إنشاء",
  add: "إضافة",
  remove: "إزالة",
  close: "إغلاق",
  open: "فتح",
  details: "التفاصيل",
  notes: "ملاحظات",
  passport: "معلومات جواز السفر",
  totalSpend: "إجمالي الإنفاق",
  bookingHistory: "سجل الحجوزات",
  route: "المسار",
  pnr: "رمز الحجز",
  ticketNumber: "رقم التذكرة",
  airline: "الخطوط الجوية",
  visaCountry: "دولة التأشيرة",
  hotelName: "اسم الفندق",
  checkIn: "تاريخ الوصول",
  checkOut: "تاريخ المغادرة",
  tourName: "اسم الجولة",
  costPrice: "سعر التكلفة",
  salePrice: "سعر البيع",
  agentCommission: "عمولة الوكيل",
  paymentStatus: "حالة الدفع",
  processStatus: "حالة المعالجة",
  createdAt: "تاريخ الإنشاء",
  updatedAt: "تاريخ التحديث",
  quickActions: "إجراءات سريعة",
  generateReport: "إنشاء تقرير",
  auditLogs: "سجلات التدقيق",
  agencies: "الوكالات",
  subscriptions: "الاشتراكات",
  plans: "الخطط",
  payments: "المدفوعات",
  usage: "الاستخدام",
  reset: "إعادة تعيين",
  suspend: "تعليق",
  unsuspend: "إلغاء التعليق",
  deleteAccount: "حذف الحساب",
  areYouSure: "هل أنت متأكد؟",
  thisCannotBeUndone: "لا يمكن التراجع عن هذا الإجراء.",
  success: "نجاح",
  warning: "تحذير",
  info: "معلومة",
  errorOccurred: "حدث خطأ",
  tryAgain: "يرجى المحاولة مرة أخرى",
  loading: "جاري التحميل",
  noData: "لا توجد بيانات متاحة",
  noResults: "لم يتم العثور على نتائج",
  showMore: "عرض المزيد",
  showLess: "عرض أقل",
  itemsPerPage: "عناصر لكل صفحة",
  of: "من",
  page: "صفحة",
  previous: "السابق",
  greeting: "صباح الخير",
  greetingAfternoon: "مساء الخير",
  greetingEvening: "مساء الخير",
  agencyProfile: "ملف الوكالة",
};

const dictionaries: Record<Locale, Dictionary> = { en, ar };

interface LanguageContextType {
  language: Locale;
  setLanguage: (lang: Locale) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
  isRTL: boolean;
}

const LanguageContext = createContext<LanguageContextType>({
  language: "en",
  setLanguage: () => {},
  t: (key: string) => key,
  dir: "ltr",
  isRTL: false,
});

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Locale>("en");

  useEffect(() => {
    const saved = (typeof window !== "undefined" && localStorage.getItem("tdp-lang")) as Locale | null;
    if (saved && (saved === "en" || saved === "ar")) {
      setLanguageState(saved);
      document.documentElement.dir = saved === "ar" ? "rtl" : "ltr";
      document.documentElement.lang = saved;
    }
  }, []);

  const setLanguage = useCallback((lang: Locale) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      localStorage.setItem("tdp-lang", lang);
    }
    document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = lang;
  }, []);

  const t = useCallback(
    (key: string) => {
      return dictionaries[language][key] || key;
    },
    [language]
  );

  const dir = language === "ar" ? "rtl" : "ltr";
  const isRTL = language === "ar";

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, dir, isRTL }}>
      <div dir={dir}>{children}</div>
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
